### ISSUE TITLE
Add Postgres psycopg2 package to Dockerfile

### ISSUE THREAD

**Issue by antaenc** [Senzing/docker-xterm#12]
To use tooling with PostgreSQL, need the psycopg2 module baked into container. 

This involves:

1. Removing `psycopg2-binary` pip package
1. Adding `libpq-dev` and `python-dev` system packages
1. Adding `psycopg2` pip package
1. Updating the `BASE_IMAGE` to senzing/senzing-base:1.5.5

See changes in https://github.com/Senzing/docker-xterm/compare/1.0.3...1.0.5

**Comment by docktermj** [comment]
Is this the module requested?

https://github.com/Senzing/docker-xterm/blob/45c7e85282657503a686f29d1c387980e9ea8c71/Dockerfile#L63

**Comment by docktermj** [comment]
Reference: https://stackoverflow.com/questions/11583714/install-psycopg2-on-ubuntu

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/docker-xterm/pull/13
2. https://github.com/Senzing/docker-xterm/pull/15
