### ISSUE TITLE
Add telnet package to Dockerfile

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-xterm#14]
Add the `telnet` package to the list of installed system packages at
https://github.com/Senzing/docker-xterm/blob/6c0b69d9d90b4f614958f6f005f69ac3ce2bc2a3/Dockerfile#L19-L37

Make sure system packages are listed in alphabetical order for easier searching and duplicate detection.

**Comment by antaenc** [comment]
@SamMacy please can you change ipython to be ipython3 instead and add zip to the apt install. 

Discussed with @docktermj today - can you also make the same changes to any user facing containers such as ssh, debug, console.

**Comment by docktermj** [comment]
This repository has been fixed via https://github.com/Senzing/docker-xterm/issues/16

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/docker-xterm/pull/18
